### ISSUE TITLE
CannotResolveAssetNameException: wait instead of immediate fail?

### ISSUE THREAD

**Issue by jkuchar** [contributte/webpack#11]
Hi! I see quite often `CannotResolveAssetNameException` (during webpack compile time).

![image](https://user-images.githubusercontent.com/133822/49360996-17a8a880-f6db-11e8-80f6-3662a88b45cd.png)

What about waiting few seconds till it compiles and then serve response on localhost. This would save me lot of angry page refreshes. ;) And I will get page rendered ASAP.

**Comment by jiripudil** [comment]
Good news, I've added the `timeout` option to manifest loading. Could you please check #34 and confirm that it solves your issue? Thank you :)
