### ISSUE TITLE
Contributted

### ISSUE THREAD

**Issue by f3l1x** [contributte/webpack#23]
- [x] packagist
- [x] contributte site
- [x] namespace
- [x] docs
- [x] readme
- [x] tag `2.0.0`

**Comment by jiripudil** [comment]
@f3l1x první dva body jsou na tebe, já pak otaguju 2.0.0 a bude ✅

**Comment by f3l1x** [comment]
Packagist ready https://packagist.org/packages/contributte/webpack

**Comment by jiripudil** [comment]
Aaaand released [2.0.0](https://github.com/contributte/webpack/releases/tag/2.0.0) 🎉
