### ISSUE TITLE
No composer package

### ISSUE THREAD

**Issue by stanley89** [contributte/webpack#24]
Hello, composer package for this (renamed) repository does not exist yet. Could you please create id?
```
$ composer require contributte/webpack

  [InvalidArgumentException]                                                   
  Could not find a matching version of package contributte/webpack. Check the  
   package spelling, your version constraint and that the package is availabl  
  e in a stability which matches your minimum-stability (stable).     
```

**Comment by jiripudil** [comment]
Hello, please give us some time to process the transition. Unfortunately I don't have privileges to submit packages under the `contributte` vendor, so it's up to @f3l1x now. You can watch #23 for updates.
