### ISSUE TITLE
Use different DevServer/Http/Client class

### ISSUE THREAD

**Issue by janfejtek** [contributte/webpack#25]
The CurlClient class is hard coded in extension.
https://github.com/contributte/webpack/blob/e2e749931d02e55d4581f6e7b02f6ff2e45898bc/src/DI/WebpackExtension.php#L92

Would it be possible to define it in config as well?

My use case is that I need to check REMOTE_ADDR instead of localhost for a running dev server.

**Comment by jiripudil** [comment]
Hello,

I'm not sure changing the client implementation is the right place to solve your use case 🤔 The dev server URL is configurable and you should be able to get the REMOTE_ADDR there using [dynamic parameters](https://doc.nette.org/en/3.0/bootstrap#toc-dynamic-parameters).

But in general, we sure can make it configurable. Could you send a pull request?

**Comment by janfejtek** [comment]
You are right, dynamic parameters are nicer solution and it works great. 👍

But just in case somebody needs it in future I will send PR anyway.

**Comment by jiripudil** [comment]
Cool, thank you!
