### ISSUE TITLE
Missing nette/utils dependency

### ISSUE THREAD

**Issue by janfejtek** [contributte/webpack#42]
Hi,
this change in version 2.3.0 
https://github.com/contributte/webpack/commit/44196834c786abc15a66805f0e9d467b4923d03a#diff-c7d4b68a69f6e026937f141eb6c09d55d5f983864fff53d71477121e3eacc02dR72 
requires nette/utils to be version 4.0 https://github.com/nette/utils/commit/c6fd05c8341097c9b1d5451742b38d745eb9bc63#diff-aec44a5c943d5c43c5dc277e89cb3183219f507c84950749b5423913670a1defR65

but nette/utils is not explicitly mentioned in composer.json file. So after update, when I have nette/utils 3.0, it crashes on `Unknown named parameter $forceArrays`

**Comment by jiripudil** [comment]
Thanks for the report, this was indeed an oversight. Fixed in 2.3.1
